eonu/sequentia

CHANGELOG.md, examples/Pen-Tip Trajectories (Example).ipynb
- Remove HMM complexity comment from trajectories example notebook.
=> [patch:docs] Remove HMM complexity comment

README.md, examples/Pen-Tip Trajectories (Example).ipynb, lib/sequentia/classifiers/dtwknn/dtwknn.py, lib/sequentia/classifiers/hmm/hmm.py, setup.py
- Add multi-processing support for `DTWKNN` predictions.
=> [add:lib] Add multi-processing support for DTWKNN

README.md
- Add reference to Pomegranate paper and package ([jmschrei/pomegranate](https://github.com/jmschrei/pomegranate)).
=> [add:docs] Add reference to Pomegranate paper and package

README.md, notebooks/Pen-Tip Trajectories (Example).ipynb
- CGI-escape nbviewer notebook URLs.
=> [patch:docs] CGI-escape nbviewer notebook URLs

lib/sequentia/classifiers/dtwknn/dtwknn.py, lib/sequentia/preprocessing/preprocess.py, notebooks/2 - Preprocessing (Tutorial).ipynb
- Simplify `Preprocess` `transform()` function.
=> [patch:lib] Simplify Preprocess transform() function

lib/sequentia/classifiers/dtwknn/dtwknn.py, lib/sequentia/preprocessing/preprocess.py
- Remove unnecessary package imports.
=> [rm:lib] Remove unnecessary package imports

lib/sequentia/classifiers/dtwknn/dtwknn.py, lib/sequentia/classifiers/hmm/hmm_classifier.py, setup.py
- Add multi-processing support for `DTWKNN` predictions. ([#29](https://github.com/eonu/sequentia/pull/29))
- Rename the `fit_transform()` function in `Preprocess` to `transform()` since there is nothing being fitted. ([#35](https://github.com/eonu/sequentia/pull/35))
- Modify package classifiers in `setup.py`: ([#31](https://github.com/eonu/sequentia/pull/31))
- Set development status classifier to `Pre-Alpha`.
- Add Python version classifiers for v3.5+.
- Specify UNIX and macOS operating system classifiers.
- Finish tutorial and example notebooks. ([#35](https://github.com/eonu/sequentia/pull/35))
- Rename `examples` directory to `notebooks`. ([#32](https://github.com/eonu/sequentia/pull/32))
- Host notebooks statically on [`nbviewer`](https://github.com/jupyter/nbviewer). …
=> [release] 0.2.0 🎉 (‖)

CHANGELOG.md
- Add `CHANGELOG.md` entry for v0.2.0.
=> [add:docs] Add changelog entry for v0.2.0

CHANGELOG.md, docs/conf.py, setup.py
- Add proper documentation, hosted on [Read The Docs](https://sequentia.readthedocs.io/en/latest). ([#40](https://github.com/eonu/sequentia/pull/40), [#41](https://github.com/eonu/sequentia/pull/41))
=> [release] 0.3.0 🎉 (📚)

README.md
- Center `README` header on PyPi.
=> [patch:docs] Center README header on PyPI

LICENSE
=> [patch:pkg] Add end year to LICENSE

docs/_includes/examples/preprocessing/preprocess.py, lib/sequentia/preprocessing/methods.py, lib/sequentia/preprocessing/preprocess.py
- Add restrictions on preprocessing parameters: downsample factor and window size.
=> [patch:lib] Add restrictions on downsample factor and window size

docs/sections/preprocessing/filtrate.rst, lib/sequentia/preprocessing/methods.py, lib/sequentia/preprocessing/preprocess.py, notebooks/2 - Preprocessing (Tutorial).ipynb
- Use median filtering and decimation downsampling by default.
=> [patch:lib] Change method defaults for filtering and downsampling

README.md
- Add supported topologies (left-right and ergodic) to feature list.
=> [add:docs] Add supported topologies to feature list

docs/_includes/examples/preprocessing/preprocess.py, lib/sequentia/preprocessing/preprocess.py, notebooks/2 - Preprocessing (Tutorial).ipynb
- Add `Preprocess.summary()` to display an ordered summary of preprocessing transformations.
=> [add:lib] Add summary method for preprocessing transformations

lib/sequentia/classifiers/dtwknn/dtwknn.py, lib/sequentia/classifiers/hmm/hmm.py, lib/sequentia/classifiers/hmm/hmm_classifier.py, lib/sequentia/internals/__init__.py, lib/sequentia/internals/validator.py, lib/sequentia/preprocessing/methods.py, lib/sequentia/preprocessing/preprocess.py, lib/tests/lib/internals/test_validator.py
- Internalize `Validator` class (prefix class name with `_`).
=> [patch:lib] Internalize Validator class

lib/sequentia/preprocessing/preprocess.py
- Fix `Preprocess.downsample()` documentation.
=> [patch:docs] Fix Preprocess.downsample() documentation

CHANGELOG.md
- Fix changelog reference (PR #52).
=> [patch:docs] Fix changelog reference (PR #52)

README.md
- Add standardization to `README.md` features section.
=> [add:docs] Add standardization to README features section

CHANGELOG.md, docs/conf.py, setup.py
- Add package tests and Travis CI support. ([#56](https://github.com/eonu/sequentia/pull/56))
- Remove Python v3.8+ support. ([#56](https://github.com/eonu/sequentia/pull/56))
- Rename `normalize` preprocessing method to `center`, since it just centers an observation sequence. ([#62](https://github.com/eonu/sequentia/pull/62))
- Add `standardize` preprocessing method for standardizing (standard scaling) an observation sequence. ([#63](https://github.com/eonu/sequentia/pull/63))
- Add `trim_zeros` preprocessing method for removing zero-observations from an observation sequence. ([#67](https://github.com/eonu/sequentia/pull/67))
- (_Internal_) Add `Validator.random_state` for validating random state objects and seeds. ([#56](https://github.com/eonu/sequentia/pull/56))
- (_Internal_) …
=> [release] 0.6.0 🎉 (✅)

notebooks/Pen-Tip Trajectories (Example).ipynb
- Fix `DTWKNN` prediction time comment.
=> [patch:docs] Fix DTWKNN prediction time comment

setup.py
- Add [documentation link](https://sequentia.readthedocs.io/en/latest) to `setup.py`.
=> [patch:pkg] Add documentation link to setup.py

README.md
- Fix typos and update preprocessing information in `README.md`.
=> [patch:docs] Update README.md 

lib/sequentia/__init__.py
=> [patch:pkg] Clean up package imports

docs/conf.py, setup.py
- Clean up package imports. ([#77](https://github.com/eonu/sequentia/pull/77))
- Rework `preprocessing` module. ([#75](https://github.com/eonu/sequentia/pull/75))
- Fix typos and update preprocessing information in `README.md`. ([#76](https://github.com/eonu/sequentia/pull/76))
=> [release] 0.7.0a1 🎉

lib/sequentia/classifiers/dtwknn/dtwknn.py, lib/sequentia/classifiers/hmm/hmm.py, lib/sequentia/classifiers/hmm/hmm_classifier.py, lib/test/lib/classifiers/dtwknn/test_dtwknn.py, lib/test/lib/classifiers/hmm/test_hmm.py, lib/test/lib/classifiers/hmm/test_hmm_classifier.py, lib/test/lib/classifiers/hmm/test_topologies.py, lib/test/lib/internals/test_validator.py, lib/test/lib/preprocessing/test_preprocess.py, lib/test/lib/preprocessing/test_transforms.py
=> [patch:lib] Simplify package imports

docs/sections/classifiers/hmm.rst
- Fix HMM topology documentation typo.
=> [patch:docs] Fix HMM topology documentation typo

lib/sequentia/classifiers/dtwknn/dtwknn.py
- Remove nested helper functions in `DTWKNN.predict()`.
=> [patch:lib] Remove nested helper functions in DTWKNN.predict()

docs/sections/classifiers/hmm.rst, lib/sequentia/classifiers/__init__.py, lib/sequentia/classifiers/hmm/__init__.py, lib/sequentia/classifiers/hmm/hmm.py, lib/sequentia/classifiers/hmm/topologies/__init__.py, lib/sequentia/classifiers/hmm/topologies/left_right.py, lib/sequentia/classifiers/hmm/topologies/strict_left_right.py, lib/test/lib/classifiers/hmm/test_hmm.py, lib/test/lib/classifiers/hmm/test_topologies.py
- Add strict left-right HMM topology.
=> [add:lib] Add strict left-right HMM topology

lib/sequentia/classifiers/hmm/hmm.py
- Fix strict left-right topology serialization.
=> [patch:lib] Fix strict left-right topology serialization

lib/test/lib/classifiers/hmm/test_gmmhmm.py
- Fix `GMMHMM` NaN values in tests.
=> [patch:tests] Fix GMMHMM NaN values in tests

README.md, lib/sequentia/classifiers/dtwknn/dtwknn.py, lib/sequentia/internals/validator.py
- Implement distance-weighted DTW-kNN predictions.
- Add `Validator.func()` for validating callables.
=> [add:lib] Implement distance-weighted DTW-kNN predictions

docs/_includes/examples/classifiers/knn_classifier.py, docs/index.rst, docs/sections/classifiers/knn.rst, lib/sequentia/classifiers/__init__.py, lib/sequentia/classifiers/dtwknn/__init__.py, lib/sequentia/classifiers/knn/__init__.py, lib/sequentia/classifiers/knn/knn_classifier.py, lib/test/lib/classifiers/hmm/test_hmm.py, lib/test/lib/classifiers/knn/test_knn_classifier.py, notebooks/1 - Input Format (Tutorial).ipynb, notebooks/Pen-Tip Trajectories (Example).ipynb
- Rename `DTWKNN` to `KNNClassifier`.
=> [patch:lib] Rename DTWKNN to KNNClassifier

CHANGELOG.md, docs/conf.py, lib/sequentia/__init__.py, setup.py
- Add package version specifier `sequentia.__version__`. (see #96)
=> [add:lib] Add package version specifier

LICENSE, README.md, docs/conf.py, lib/sequentia/classifiers/knn/knn_classifier.py
=> [patch:docs] Update copyright year

docs/conf.py, lib/sequentia/classifiers/knn/knn_classifier.py
- Simplify sphinx package import directives (see #97).
=> [patch:docs] Simplify sphinx package import directives

CHANGELOG.md, lib/sequentia/__init__.py, lib/sequentia/classifiers/knn/knn_classifier.py, setup.py
- Stop referring to sequences as temporal, as non-temporal sequences can also be used. ([#103](https://github.com/eonu/sequentia/pull/103))
=> [release] 0.7.2 🎉

docs/conf.py
- Remove references to `sigment`.
=> [patch:docs] Remove references to Sigment

docs/sections/classifiers/gmmhmm.rst, lib/sequentia/classifiers/knn/knn_classifier.py
- Simplify `GMMHMM` documentation.
=> [patch:docs] Simplify GMMHMM documentation

README.md, setup.py
- Add @Prhmma as a contributor for #145.
=> [patch:docs] Update contributors

lib/sequentia/classifiers/hmm/gmmhmm.py, lib/test/lib/classifiers/hmm/test_gmmhmm.py, lib/test/support/__init__.py, lib/test/support/assertions.py
- Add selective `GMMHMM` parameter freezing/unfreezing (see #150).
=> [patch:lib] Add selective GMMHMM parameter freezing/unfreezing

lib/sequentia/classifiers/hmm/gmmhmm.py, lib/test/lib/classifiers/hmm/test_gmmhmm.py
- Add properties for GMM emission distribution parameters (see #153).
=> [patch:lib] Add properties for GMM emission parameters

lib/sequentia/classifiers/hmm/gmmhmm.py, lib/sequentia/classifiers/hmm/hmm_classifier.py, lib/sequentia/classifiers/knn/knn_classifier.py, lib/sequentia/internals/validator.py, lib/test/lib/classifiers/hmm/test_gmmhmm.py, lib/test/lib/classifiers/hmm/test_hmm_classifier.py, lib/test/lib/classifiers/knn/test_knn_classifier.py
- Add validation for checking fitted parameters (see #157).
- Clean up `__repr__` for `GMMHMM`, `HMMClassifier` and `KNNClassifier`.
=> [patch:lib] Add validation for checking fitted parameters

lib/sequentia/classifiers/hmm/gmmhmm.py, lib/sequentia/classifiers/hmm/hmm_classifier.py, lib/sequentia/classifiers/knn/knn_classifier.py, lib/sequentia/internals/validator.py, lib/sequentia/preprocessing/preprocess.py, lib/sequentia/preprocessing/transforms.py, lib/test/lib/internals/test_validator.py
- Prefix `_Validator` functions with `is_` (see #159).
=> [patch:lib] Prefix validation functions with is_

lib/sequentia/classifiers/hmm/gmmhmm.py, lib/test/lib/classifiers/hmm/test_gmmhmm.py
- Add access to Baum-Welch algorithm convergence monitor (see #139).
=> [patch:lib] Add access to Baum-Welch algorithm convergence monitor

lib/sequentia/internals/validator.py, lib/test/lib/internals/test_validator.py
- Fix validation for univariate sequences.
- Clean up validation logical expressions.
=> [patch:lib] Fix validation for univariate sequences

README.md
- Clean up `README.md` and add examples.
=> [patch:docs] Clean up README.md and add examples

CHANGELOG.md, README.md, lib/sequentia/__init__.py, lib/sequentia/internals/validator.py, lib/test/lib/internals/test_validator.py, setup.py
- Fix validation for univariate sequences. ([#164](https://github.com/eonu/sequentia/pull/164))
- Clean up `README.md` and add examples. ([#165](https://github.com/eonu/sequentia/pull/165))
- Clean up validation logical expressions. ([#164](https://github.com/eonu/sequentia/pull/164))
=> [release] 0.11.1 🎉

README.md
=> [patch:docs] Fix typo in README.md

README.md
=> [patch:docs] Fix wording in README.md

CONTRIBUTING.md
- Fix patch description in `CONTRIBUTING.md`.
=> [patch:docs] Fix patch description in CONTRIBUTING.md

setup.py
- Bump development status classifier to beta.
=> [patch:pkg] Bump development status classifier to beta

lib/sequentia/classifiers/knn/knn_classifier.py
- Simplifies the `KNNClassifier` interface by assuming a `None` weighting is uniform.
- Removes some validation for weightings.
=> [patch:lib] Remove 'uniform' KNNClassifier weighting option

lib/sequentia/classifiers/hmm/hmm_classifier.py, lib/sequentia/classifiers/knn/knn_classifier.py
=> [patch:lib] Update HMMClassifier structure to match KNNClassifier

README.md
=> [add:docs] Add README.md navigation

setup.py
- Fix package versions for documentation dependencies.
=> [patch:docs] Fix versions for docs deps

README.md, setup.py
- Add `numpydoc` version specifier.
=> [add:docs] Add numpydoc version specifier

README.md
- Remove `TorchFSDD` reference.
=> [patch:docs] Fix TorchFSDD typo

lib/test/lib/classifiers/hmm/test_gmmhmm.py, lib/test/lib/classifiers/hmm/test_hmm_classifier.py
- Update HMM tests to use `datasets` module.
=> [patch:test] Update HMM tests to use `datasets` module

CONTRIBUTING.md
- Update `CONTRIBUTING.md` CI instructions.
=> [patch:docs] Update `CONTRIBUTING.md` CI instructions

setup.py
- Add `digits.npz` as package data in `setup.py`.
=> [add:pkg] Add `digits.npz` as package data in `setup.py`

CHANGELOG.md, lib/sequentia/__init__.py, setup.py
- Add `digits.npz` as package data in `setup.py`. ([#221](https://github.com/eonu/sequentia/issues/221))
=> [release] v0.13.1 🎉

lib/sequentia/datasets/random_sequences.py
- Fix `load_random_sequences` docstring typo.
=> Fix `load_random_sequences` docstring typo

setup.py
- Upgrade development status classifier to stable/production.
=> upgrade to stable dev status classifier [skip ci]

lib/sequentia/preprocessing/transforms.py
- Remove scikit-learn validation constraints from `IndependentFunctionTransformer`.
=> remove `IndependentFunctionTransformer` sklearn validation

lib/sequentia/preprocessing/transforms.py
- Change default `mean_filter`/`median_filter` width to 5.
=> change default `mean_filter`/`median_filter` width to 5

.gitignore, CHANGELOG.md, CODE_OF_CONDUCT.md, CONTRIBUTING.md, LICENSE, lib/sequentia/__init__.py, lib/sequentia/preprocessing/transforms.py
- Remove `scikit-learn` validation constraints from `IndependentFunctionTransformer`. ([#237](https://github.com/eonu/sequentia/pull/237))
- Change default `mean_filter`/`median_filter` width to 5. ([#238](https://github.com/eonu/sequentia/pull/238))
- Update repository documentation. ([#239](https://github.com/eonu/sequentia/pull/239))
=> release 1.1.1

mise.toml, pyproject.toml, sequentia/_internal/_typing.py, sequentia/_internal/_validation.py, tests/unit/test_pipeline.py
=> feat: add `mise.toml` and support `numpy>=2`

.circleci/config.yml, mise.toml, pyproject.toml
=> feat: add python v3.13 support

sequentia/models/knn/regressor.py
=> docs: fix `KNNRegressor.window` docstring typo

README.md
- Add speed section to introduction.
- Mention multi-processed training for HMMClassifier.
- Mention fallback for `dtaidistance` C libraries.
=> docs: update `README.md` features
