.gitattributes, notebooks/Pen-Tip Trajectories (Example).ipynb
- Add `.gitattributes` and hide Jupyter notebooks from repository language classification.
- Use explicit HTML anchors for nbviewer URLs in notebooks.
=> [patch:docs] Use explicit HTML anchors for nbviewer URLs

docs/conf.py
- Specify `docs/index.rst` as the master document for Sphinx.
=> [patch:docs] Specify index.rst as master document

docs/_includes/examples/classifiers/hmm_classifier.py
- Add explicit labels to `evaluate()` in `HMMClassifier` example.
=> [patch:docs] Add explicit labels to HMMClassifier example

lib/sequentia/classifiers/dtwknn/dtwknn.py
- Re-add `euclidean` metric as `DTWKNN` default.
=> [patch:lib] Re-add 'euclidean' metric as DTWKNN default

CHANGELOG.md, docs/conf.py, setup.py
- Re-add `euclidean` metric as `DTWKNN` default. ([#43](https://github.com/eonu/sequentia/pull/43))
- Add explicit labels to `evaluate()` in `HMMClassifier` example. ([#44](https://github.com/eonu/sequentia/pull/44))
=> [release] 0.4.0 🎉 (🛠)

lib/sequentia/preprocessing/preprocess.py
- Allow `Preprocess` class to be used to apply preprocessing transformations to a single observation sequence.
=> [patch:lib] Allow Preprocess class to be used for single sequences

CHANGELOG.md, docs/conf.py, setup.py
- Add `Preprocess.summary()` to display an ordered summary of preprocessing transformations. ([#54](https://github.com/eonu/sequentia/pull/54))
- Add mean and median filtering preprocessing methods. ([#48](https://github.com/eonu/sequentia/pull/48))
- Use median filtering and decimation downsampling by default. ([#53](https://github.com/eonu/sequentia/pull/52))
- Modify preprocessing boundary conditions ([#51](https://github.com/eonu/sequentia/pull/51)):
- Use a bi-directional window for filtering to resolve boundary problems.
- Modify downsampling method to downsample residual observations.
- Add supported topologies (left-right and ergodic) to feature list. ([#53](https://github.com/eonu/sequentia/pull/53))
- Add restrictions on preprocessing parameters: downsample factor and window …
=> [release] 0.5.0 🎉 (🕸)

README.md, docs/sections/classifiers/hmm.rst, lib/sequentia/classifiers/hmm/hmm_classifier.py, notebooks/1 - Input Format (Tutorial).ipynb, notebooks/Pen-Tip Trajectories (Example).ipynb
- As the HMM classifier is not a true ensemble of HMMs (since each HMM doesn't really contribute to the classification), it is no longer referred to as an ensemble.
=> [rm:lib] Don't refer to HMM classifier as ensemble

lib/sequentia/classifiers/dtwknn/dtwknn.py, lib/sequentia/classifiers/hmm/hmm.py, lib/sequentia/classifiers/hmm/hmm_classifier.py, lib/sequentia/internals/validator.py, lib/sequentia/preprocessing/methods.py, lib/sequentia/preprocessing/preprocess.py, lib/test/lib/internals/test_validator.py, notebooks/1 - Input Format (Tutorial).ipynb, notebooks/2 - Preprocessing (Tutorial).ipynb, notebooks/Pen-Tip Trajectories (Example).ipynb
- Remove strict requirement of Numpy arrays being two-dimensional by using `numpy.atleast_2d` to convert one-dimensional arrays into 2D.
=> [patch:lib] Remove strict 2D np.ndarray (use np.atleast_2d)

CHANGELOG.md, docs/conf.py, setup.py
- Remove strict requirement of Numpy arrays being two-dimensional by using `numpy.atleast_2d` to convert one-dimensional arrays into 2D. ([#70](https://github.com/eonu/sequentia/pull/70))
- As the HMM classifier is not a true ensemble of HMMs (since each HMM doesn't really contribute to the classification), it is no longer referred to as an ensemble. ([#69](https://github.com/eonu/sequentia/pull/69))
=> [release] 0.6.1 🎉

setup.py
- Fix `pomegranate` to v0.12.0 for the time being, due to wheel-building issues in Travis builds.
=> [patch:ci] Fix pomegranate to v0.12.0

README.md, docs/_includes/examples/classifiers/gmmhmm.py, docs/conf.py, docs/sections/classifiers/hmm.rst, lib/sequentia/classifiers/__init__.py, lib/sequentia/classifiers/hmm/__init__.py, lib/sequentia/classifiers/hmm/gmmhmm.py, lib/sequentia/classifiers/hmm/hmm.py, lib/sequentia/classifiers/hmm/hmm_classifier.py, lib/test/lib/classifiers/hmm/test_gmmhmm.py, lib/test/lib/classifiers/hmm/test_hmm.py
=> [add:lib] Implement GMM-HMMs

lib/sequentia/classifiers/knn/knn_classifier.py
- Fix deserialization for `KNNClassifier`.
- Sort HDF5 keys before loading as `numpy.ndarray`s.
- Pass `weighting` function into deserialization constructor.
=> [patch:lib] Fix deserialization for KNNClassifier

README.md, docs/index.rst, lib/sequentia/classifiers/hmm/gmmhmm.py, lib/sequentia/classifiers/hmm/hmm.py, lib/sequentia/classifiers/knn/knn_classifier.py, notebooks/Pen-Tip Trajectories (Example).ipynb, setup.py
- Stop referring to sequences as temporal, as non-temporal sequences can also be used.
=> [patch:docs] Stop referring to sequences as temporal

lib/sequentia/classifiers/knn/knn_classifier.py
- Add `original_labels` documentation to `KNNClassifier`.
=> [patch:docs] Add original_labels documentation to KNNClassifier

setup.py
encoding problem in setup.py caused a problem installing the package from pip.
adding utf-8 solved it.
=> [patch:pkg] Fix setup.py encoding problem

docs/conf.py, docs/robots.txt
- Add `docs/robots.txt` and `sphinx-version-warning` package to prevent search engines from indexing old package versions (see #143).
=> [patch:docs] Prevent search engines from indexing old versions

README.md
- Add classifier documentation links to `README.md`.
=> [patch:docs] Add classifier documentation links to README.md

README.md
- Add build status to `README.md`.
=> [patch:docs] Add build status to README.md

setup.py
Adds a version specifier for `Jinja2` to get around existing RTD issues (see https://github.com/readthedocs/readthedocs.org/issues/9038).
=> [patch:docs] Add Jinja2 dependency for docs

CONTRIBUTING.md, README.md
- Hard-link `README.md` images to improve rendering on PyPI.
- Remove `pip install` extras information from `README.md`.
- Update `CONTRIBUTING.md`.
=> Hard-link `README.md` images + update `CONTRIBUTING.md`

README.md, lib/sequentia/models/hmm/classifier.py, lib/sequentia/models/knn/base.py, lib/sequentia/models/knn/classifier.py, setup.py
- Set `max_nbytes=None` to fix read-only buffer source array error in `joblib.Parallel` (see https://github.com/scikit-learn/scikit-learn/issues/7981).
=> fix parallel read-only buffer source array

CHANGELOG.md, README.md, docs/index.rst, docs/sections/models/hmm/classifier.rst, docs/sections/models/knn/classifier.rst, docs/sections/models/knn/regressor.rst, docs/sections/preprocessing/index.rst, docs/sections/preprocessing/pipeline.rst, docs/sections/preprocessing/transforms/filters.rst, docs/sections/preprocessing/transforms/function_transformer.rst, docs/sections/preprocessing/transforms/index.rst, lib/sequentia/__init__.py, lib/sequentia/models/base.py, lib/sequentia/models/hmm/classifier.py, lib/sequentia/models/knn/base.py, lib/sequentia/models/knn/classifier.py, lib/sequentia/models/knn/regressor.py, lib/sequentia/pipeline.py, lib/sequentia/preprocessing/base.py, lib/sequentia/preprocessing/transforms.py, lib/test/lib/preprocessing/test_transforms.py, lib/test/lib/test_pipeline.py, setup.py
- Set `max_nbytes=None` to fix read-only buffer source array error in `joblib.Parallel` (see https://github.com/scikit-learn/scikit-learn/issues/7981). ([#235](https://github.com/eonu/sequentia/pull/235))
- Added `sequentia.preprocessing` module with [`sklearn.preprocessing`](https://scikit-learn.org/stable/modules/classes.html#module-sklearn.preprocessing) compatibility. ([#234](https://github.com/eonu/sequentia/pull/234))
- Added `sequentia.pipeline` module for [`sklearn.pipeline`](https://scikit-learn.org/stable/modules/classes.html#module-sklearn.pipeline) compatibility. ([#234](https://github.com/eonu/sequentia/pull/234))
- Upgrade `sklearn` version specifier from `>=0.22` to `>=1.0`. ([#234](https://github.com/eonu/sequentia/pull/234))
- Upgrade development status classifier to …
=> release 1.1.0

.gitignore, CODE_OF_CONDUCT.md, CONTRIBUTING.md, LICENSE
- Update repository documentation.
=> update repo docs

sequentia/models/knn/classifier.py
Was incorrectly using `np.log(self.predict_scores(...))` instead of `np.log(self.predict_probs(...))`.
Fixes #246.
=> fix: use log probs for `KNNClassifier.predict_log_proba`

sequentia/models/knn/base.py, tests/unit/test_models/knn/test_classifier.py
Fixes #250 (was calling wrong DTW function).
=> fix: call `KNNMixin._dtw1d` when `independent=True`

docs/source/sections/model_selection/searching.rst, sequentia/model_selection/__init__.py, sequentia/model_selection/_search.py, sequentia/models/hmm/classifier.py, sequentia/models/hmm/variants/__init__.py, tests/unit/test_model_selection.py, tests/unit/test_models/hmm/test_classifier.py
- Adds the ability to specify a HMM variant and configuration in `HMMClassifier.__init__`.
- This enables the use of `sequentia.model_selection` on `HMMClassifier` objects.
=> feat: add model spec support to `HMMClassifier.__init__`

docs/source/sections/models/index.rst, sequentia/model_selection/_search.py, sequentia/models/hmm/classifier.py, tests/unit/test_models/hmm/test_classifier.py
Enables multiprocessed fitting for `HMMClassifier` if not providing pre-fitted HMMs.
=> feat: add `HMMClassifier.fit` multiprocessing

benchmarks/test_pyts.py, benchmarks/test_sequentia.py, benchmarks/test_sktime.py, sequentia/models/hmm/classifier.py, sequentia/models/knn/base.py, sequentia/models/knn/classifier.py
- Enable memmapping by removing `max_nbytes=None`.
- Change `mmap_mode="r"` to `mmap_mode="r+"` to fix buffer error.
=> fix: enable `joblib.Parallel` memory mapping

sequentia/models/knn/classifier.py, sequentia/models/knn/regressor.py
Set `use_c=True` by default for `KNNClassifier`/`KNNRegressor`.
=> feat: set `use_c=True` by default for `KNNClassifier`/`KNNRegressor`
